{% set version = "4.3.0" %}

package:
  name: ejson-kms
  version: {{ version }}

source:
  url: https://github.com/adrienkohlbecker/ejson-kms/archive/{{ version }}.tar.gz
  sha256: b7422dced1392e7262383c3da3750ad88f8b4a506e281c1a73b41ebf5b2463c9

build:
  number: 0

requirements:
  build:
    - {{ compiler('go-nocgo') }}
    - go-licenses

test:
  commands:
    - ejson-kms --help

about:
  home: https://github.com/ejson-kms/ejson-kms
  license: MIT
  license_file:
    - LICENSE
    - license-files/
  summary: ejson-kms is a utility for managing a collection of secrets in source control using AWS KMS
  dev_url: https://github.com/ejson-kms/ejson-kms

extra:
  recipe-maintainers:
    - danielnachun
